[package]
name = "lin-ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
tera = "1.20.0"
markdown = "=1.0.0-alpha.21"
toml = "0.8.19"
thiserror = "2.0.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
