[workspace]
members = ["core", "linguinput"]
resolver = "2"

[workspace.dependencies]
tera = "1.20.0"
markdown = "=1.0.0-alpha.21"
toml = "0.8.19"
thiserror = "2.0.3"
serde = { version = "1.0.215" }
serde_json = "1.0.133"
